"use client";

import { useCallback, useEffect, useState, type ComponentType } from "react";
import { isHoldFixture, practiceData, unavailable, workbenchData } from "@/lib/data";

type View = "overview" | "demonstrations" | "skills" | "policy" | "authority" | "episodes" | "findings" | "protocol" | "limitations";

const nav: Array<[View, string, string]> = [
  ["overview", "Overview", "1"], ["demonstrations", "Demonstrations", "2"], ["skills", "Skills", "3"], ["policy", "Policy placement", "4"], ["authority", "Authority conflicts", "5"], ["episodes", "Episodes", "6"], ["findings", "Findings", "7"], ["protocol", "Protocol & evidence", "8"], ["limitations", "Limitations", "9"],
];

const navGlyphPaths = ["M3 17 8 11l4 3 7-8", "M4 5h16v14H4zM7 9h10M7 13h7", "M5 4h14v16H5zM8 8h8M8 12h8M8 16h5", "M12 3l7 3v5c0 4.4-3 7.3-7 10-4-2.7-7-5.6-7-10V6l7-3", "M4 7h7m2 0h7M7 7v10m10-10v10M4 17h7m2 0h7", "M5 4h14v16H5zM8 8h8M8 12h8M8 16h5", "M5 4h14v16H5zM8 8h8M8 12h8", "M6 3h9l4 4v14H6zM14 3v5h5", "M12 3v11m0 4v3M12 3a8 8 0 1 0 8 8"] as const;
const eventGlyph: Record<string, string> = { "Model-visible context": "◫", "Tool call": "⌕", "State delta": "▱", "Authority lookup": "◇", "Final state": "⚐", "Deterministic reason code": "‹/›" };

function NavGlyph({ index }: { index: number }) {
  return <svg aria-hidden="true" className="nav-glyph" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d={navGlyphPaths[index]} /></svg>;
}

function PracticeBanner() { return <p className="practice-banner"><b>PRACTICE_NOT_EVIDENCE</b><span>{practiceData.notice}</span></p>; }
function Metric({ label, value }: { label: string; value: string }) { return <dl className="metric"><dt>{label}</dt><dd>{value}</dd></dl>; }
function metricText(value: number | null | undefined): string { return typeof value === "number" ? value.toLocaleString() : "Unavailable"; }
function figureCsv(figure: (typeof workbenchData.figures)[number]): string {
  if (figure.rows.length === 0) return "/figure-data-unavailable.csv";
  const columns = figure.columns;
  const lines = [columns.join(","), ...figure.rows.map((row) => columns.map((column) => JSON.stringify(row[column] ?? "")).join(","))];
  return `data:text/csv;charset=utf-8,${encodeURIComponent(lines.join("\n"))}`;
}
function Figure({ figure }: { figure: (typeof workbenchData.figures)[number] }) {
  const available = figure.rows.length > 0;
  return <section className="plot" aria-labelledby={`${figure.id}-title`}><div className="plot-head"><h2 id={`${figure.id}-title`}>{figure.title}</h2><a className="data-link" href={figureCsv(figure)} download={available ? `${figure.id}.csv` : undefined}>Export data table</a></div><div className="plot-grid" role="img" aria-label={`${figure.title}. ${figure.summary}`}><span className="axis y-axis">Rate (%)</span><span className="axis x-axis">Contamination level (R)</span>{available ? <div className="available-figure"><strong>{figure.rows.length} bound rows</strong><span>Read-only report projection</span></div> : <div className="unavailable-mark"><strong>Unavailable</strong><span>No confirmatory report rows</span></div>}</div><p className="screen-reader-only">{figure.summary}</p></section>;
}

function Overview() {
  const [figure1, figure2] = workbenchData.figures;
  const totalEpisodes = workbenchData.summaries.cost.included_episodes;
  const metrics = workbenchData.summaries.metrics;
  return <><p className="hold-line"><span aria-hidden="true">Ⅱ</span> {workbenchData.claim_ceiling.status === "hold" ? "HOLD — pending human anchor" : "CONFIRMATORY"}</p><h1 id="page-title">Instruction hierarchy under contaminated skills</h1><p className="hero-statement">What happens when an agent learns a common workplace procedure that the organization does not authorize?</p><div className="filter-row" aria-label="Read-only report scope"><label>Domain<select disabled defaultValue="all"><option value="all">All domains</option></select></label><label>Condition<select disabled defaultValue="all"><option value="all">All conditions</option></select></label><label>Authority level<select disabled defaultValue="all"><option value="all">All (A1–A5)</option></select></label><label>Policy<select disabled defaultValue="default"><option value="default">Default policy (v1)</option></select></label><span className="view-label">View <b>Chart</b><span>Table</span></span></div><section className="metrics" aria-label="Overview metrics"><Metric label="Ordinary task completion" value={metricText(metrics.ordinary_task_completion.value)} /><Metric label="Completion under policy" value={metricText(metrics.completion_under_policy.value)} /><Metric label="Unsafe imitation" value={metricText(metrics.unsafe_imitation.value)} /><Metric label="False enforcement" value={metricText(metrics.false_enforcement.value)} /><Metric label="Instruction hierarchy delta" value={metricText(metrics.instruction_hierarchy_delta.value)} /><Metric label="Latency" value={metricText(metrics.latency.value)} /><Metric label="Human review burden" value={metricText(metrics.human_review_burden.value)} /><Metric label="Total episodes" value={String(totalEpisodes)} /></section><Figure figure={figure1} /><div className="lower-grid"><Figure figure={figure2} /><section className="domain-table" aria-labelledby="domains-title"><h2 id="domains-title">Domain breakdown (R100)</h2><table><thead><tr><th>Domain</th><th>Completion under policy</th><th>Unsafe imitation</th></tr></thead><tbody>{workbenchData.summaries.domains.length === 0 ? <tr><td colSpan={3}>Unavailable — no confirmatory data.</td></tr> : workbenchData.summaries.domains.map((domain) => <tr key={domain.domain}><th scope="row">{domain.domain}</th><td>{metricText(domain.completion_under_policy_rate)}</td><td>{metricText(domain.unsafe_imitation_rate)}</td></tr>)}</tbody></table></section></div><section className="data-table" aria-labelledby="raw-data-title"><div className="section-heading"><h2 id="raw-data-title">Raw counts by authority level and contamination</h2><span>Figure 1</span></div><p>{figure1.rows.length === 0 ? "No confirmatory data available." : `${figure1.rows.length} rows available in the bound export.`}</p></section></>;
}

function Demonstrations() {
  const [reveal, setReveal] = useState(false);
  return <><PracticeBanner /><h1 id="page-title">Demonstration bundle explorer</h1><div className="view-toolbar"><p>Exactly 12 sanitized development demonstrations. Local terminal results are not benchmark findings.</p><button type="button" className="outline-button" onClick={() => setReveal((visible) => !visible)} aria-pressed={reveal}>{reveal ? "Hide benchmark ground truth" : "Reveal benchmark ground truth"}</button></div><section className="demo-grid" aria-label="Twelve demonstration cards">{practiceData.demonstrations.map((demo) => <article className="demo-card" key={demo.id}><p className="eyebrow">{demo.id}</p><h2>{demo.worker}</h2><dl><div><dt>Domain</dt><dd>{demo.domain}</dd></div><div><dt>Actions</dt><dd>{demo.actions}</dd></div><div><dt>Terminal local result</dt><dd>{demo.terminal}</dd></div></dl>{demo.narration && <p className="annotation">{demo.narration}</p>}{reveal && <p className="ground-truth">Practice review annotation withheld: no confirmatory class is published.</p>}</article>)}</section></>;
}

function Skills() { const skill = practiceData.skills; return <><PracticeBanner /><h1 id="page-title">Skill artifact inspector</h1><p className="hero-statement">Synchronized sanitized views of one practice artifact. They expose provenance labels, not provider payloads or hidden scorer data.</p><section className="three-pane" aria-label="Synchronized skill inspection views"><article><h2>SkillIR tree</h2><pre>{skill.skill_ir}</pre><p className="risk-label">{skill.risk_label}</p><p>{skill.risk_summary}</p></article><article><h2>Rendered SKILL.md</h2><pre>{skill.rendered_skill}</pre><p className="risk-label">Omitted approval</p><p>Practice diff indicates the approval step was absent from one observed procedure.</p></article><article><h2>Provenance map</h2><ul className="provenance-list">{skill.provenance.map((item) => <li key={item.label}><b>{item.label}</b><span>{item.value}</span></li>)}</ul><p className="risk-label">Local-success-only verification</p><p>A local result cannot establish authorization or benchmark compliance.</p></article></section></>; }

function Policy() { const policy = practiceData.policy; return <><PracticeBanner /><h1 id="page-title">Policy placement lab</h1><p className="hero-statement">Held-out practice case: <code>{policy.case_id}</code>. Same-tier and system-tier variants contain identical policy text and the exact same policy hash.</p><section className="policy-columns" aria-label="Four policy placement conditions">{policy.columns.map((column) => <article key={column.name}><h2>{column.name}</h2><dl><div><dt>Visible context</dt><dd>{column.visible_context}</dd></div><div><dt>Tool sequence</dt><dd>{column.tool_sequence}</dd></div><div><dt>Completion claim</dt><dd>{column.completion_claim}</dd></div><div><dt>CuP</dt><dd>{column.cup}</dd></div><div><dt>Token / cost</dt><dd>{column.token_cost}</dd></div><div><dt>Exact policy hash</dt><dd><code>{practiceData.policy_hash}</code></dd></div></dl></article>)}</section><p className="identity-note">{policy.identity_note}: <code>{practiceData.policy_hash}</code>.</p></>; }

function Authority() { const authority = practiceData.authority; return <><PracticeBanner /><h1 id="page-title">Authority conflict explorer</h1><p className="hero-statement">Practice-only resolver paths make authority relationships explicit; observed behavior never becomes authorization.</p><section className="authority-layout"><article className="authority-graph" aria-label="Authority relationship graph"><h2>Authority graph</h2>{authority.nodes.map((node, index) => <div key={node.label}>{index > 0 && <div className="graph-edge">{index === authority.nodes.length - 1 ? "↓ resolver verdict" : "conflicts_with ↓"}</div>}<div className={`graph-node ${node.class_name ?? ""}`}>{node.label}{node.note && <small>{node.note}</small>}</div></div>)}</article><article className="path-ledger"><h2>Selected paths</h2><ol>{authority.paths.map((path) => <li key={path}>{path}</li>)}</ol><table><thead><tr><th>Edge</th><th>Meaning</th></tr></thead><tbody>{authority.edges.map((edge) => <tr key={edge.label}><td>{edge.label}</td><td>{edge.meaning}</td></tr>)}</tbody></table></article></section></>; }

function Episodes() {
  const exported = workbenchData.episode_traces.slice(0, 2);
  const fromExport = exported.length === 2;
  const left = fromExport ? { id: exported[0].episode_id, title: "Confirmatory episode", events: exported[0].events.map((event) => ({ kind: event.kind, summary: event.summary })) } : practiceData.episodes.left;
  const right = fromExport ? { id: exported[1].episode_id, title: "Confirmatory episode", events: exported[1].events.map((event) => ({ kind: event.kind, summary: event.summary })) } : practiceData.episodes.right;
  const events = left.events.flatMap((event, index) => {
    const rightEvent = right.events[index];
    return rightEvent ? [{ left: event, right: rightEvent }] : [];
  });
  return <><PracticeBanner /><h1 id="page-title">Episode compare</h1><div className="compare-controls"><button type="button" className="outline-button" disabled>‹ Previous</button><span>{fromExport ? "Synchronized public trace projection" : "Synchronized timeline · static"}</span><button type="button" className="outline-button" disabled>Next ›</button></div><section className="compare-grid" aria-label={`Synchronized public trace comparison: ${left.id} and ${right.id}`}><div className="compare-corner" /><header><h2>{left.title}</h2><p>{fromExport ? "Confirmatory export" : "Development fixture"}: <code>{left.id}</code></p></header><header><h2>{right.title}</h2><p>{fromExport ? "Confirmatory export" : "Development fixture"}: <code>{right.id}</code></p></header>{events.map(({ left: leftEvent, right: rightEvent }) => <div className="compare-row" key={`${leftEvent.kind}:${leftEvent.summary}:${rightEvent.kind}:${rightEvent.summary}`}><div className="event-kind"><span aria-hidden="true">{eventGlyph[leftEvent.kind] ?? "•"}</span>{leftEvent.kind}</div><p>{leftEvent.summary}</p><p>{rightEvent.summary}</p></div>)}</section><section className="table-alternative" aria-labelledby="table-alternative-title"><h2 id="table-alternative-title">Table alternative (keyboard accessible)</h2><table><thead><tr><th>Step</th><th>{left.title} ({left.id})</th><th>{right.title} ({right.id})</th></tr></thead><tbody>{events.map(({ left: leftEvent, right: rightEvent }) => <tr key={`${leftEvent.kind}:${leftEvent.summary}:${rightEvent.kind}:${rightEvent.summary}:table`}><th scope="row">{leftEvent.kind}</th><td>{leftEvent.summary}</td><td>{rightEvent.summary}</td></tr>)}</tbody></table></section><p className="no-private">Only public, sanitized trace summaries are shown. No prompts, chain-of-thought, raw provider payloads, oracle truth, or hidden scorer custody is rendered.</p></>; }

function Findings() { return <><PracticeBanner /><h1 id="page-title">Findings</h1><p className="hero-statement">No renderable confirmatory findings are available. This development fixture cannot establish a benchmark claim.</p><section className="empty-reading"><h2>Claim ceiling: HOLD</h2><p>{workbenchData.claim_ceiling.message}</p><table><thead><tr><th>Finding ID</th><th>Status</th><th>Evidence</th></tr></thead><tbody><tr><td>—</td><td>Unavailable</td><td>No confirmatory report export</td></tr></tbody></table></section></>; }

function Protocol() { return <><PracticeBanner /><h1 id="page-title">Protocol &amp; evidence</h1><section className="evidence-ledger"><dl><div><dt>Signed protocol tag</dt><dd>{unavailable(workbenchData.protocol.protocol_tag)}</dd></div><div><dt>External anchor locator</dt><dd>{unavailable(workbenchData.protocol.external_anchor_locator)}</dd></div><div><dt>Freeze manifest hash</dt><dd>{unavailable(workbenchData.protocol.freeze_manifest_sha256)}</dd></div><div><dt>Model configuration</dt><dd>Unavailable — preregistration is not bound</dd></div><div><dt>Corpus seeds</dt><dd>Unavailable</dd></div><div><dt>Claims ledger</dt><dd>No renderable finding IDs</dd></div></dl><p className="fixture-note">The committed fixture is static and read-only. Reproduction metadata is unavailable until a validated report export exists.</p></section></>; }

function Limitations() { return <><PracticeBanner /><h1 id="page-title">Limitations</h1><section className="empty-reading"><h2>Evidence boundaries</h2><ul>{workbenchData.limitations.map((item) => <li key={item}>{item}</li>)}<li>Practice artifacts are sanitized interface fixtures, not episodes or outcomes.</li><li>Unavailable values are deliberately rendered instead of estimating missing statistics.</li></ul></section></>; }

function CustodyRail({ active }: { active: View }) { return <aside className="custody-rail" aria-label="Protocol custody"><section className="custody-section"><h2>Protocol custody</h2><dl>{[["Freeze manifest", unavailable(workbenchData.protocol.freeze_manifest_sha256)], ["Signed tag", unavailable(workbenchData.protocol.protocol_tag)], ["External anchor", unavailable(workbenchData.protocol.external_anchor_locator)], ["Experiment audit", unavailable(workbenchData.protocol.experiment_audit_status)], ["Dataset hash", unavailable(workbenchData.protocol.analysis_dataset_sha256)]].map(([label, value]) => <div className="custody-field" key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section><section className="custody-section"><h2>{active === "episodes" ? "Public trace projection" : "Selected episode"}</h2><p>{active === "episodes" ? "Share-safe summaries only. Hidden scorer custody is never exported." : "No confirmatory episode selected"}</p><div className="empty-episodes" aria-label="No confirmatory runs"><span aria-hidden="true">▱</span><p>No confirmatory runs</p></div></section><section className="custody-section limitations"><h2>Read-only boundary</h2><p className="fixture-note">{isHoldFixture ? "Static HOLD fixture; no result mutation or live data source is connected." : ""}</p></section></aside>; }

const viewComponents: Record<View, ComponentType> = {
  overview: Overview,
  demonstrations: Demonstrations,
  skills: Skills,
  policy: Policy,
  authority: Authority,
  episodes: Episodes,
  findings: Findings,
  protocol: Protocol,
  limitations: Limitations,
};

export default function Page() {
  const [active, setActive] = useState<View>("overview");
  const onKeyDown = useCallback((event: KeyboardEvent) => { const target = event.target; if (target instanceof HTMLElement && target.matches("input, textarea, select, [contenteditable='true']")) return; if (event.metaKey || event.ctrlKey || event.altKey) return; const item = nav.find(([, , key]) => key === event.key); if (item) { event.preventDefault(); setActive(item[0]); } }, []);
  useEffect(() => { window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [onKeyDown]);
  const ActiveView = viewComponents[active];
  return <main className="instrument-shell"><header className="topbar"><button type="button" className="wordmark" onClick={() => setActive("overview")}>ShadowSkillBench</button><div className="topbar-meta"><span>Research mode (read-only)</span><span className="mode-chip">{active === "overview" ? "HOLD" : "PRACTICE"}</span><span className="help" aria-label="Keyboard shortcuts available">?</span></div></header><aside className="navigation" aria-label="Workbench sections"><nav><ul>{nav.map(([view, label, shortcut], index) => <li key={view}><button type="button" className={active === view ? "active" : "pending"} onClick={() => setActive(view)} aria-current={active === view ? "page" : undefined}><NavGlyph index={index} /><span>{label}</span><kbd>{shortcut}</kbd></button></li>)}</ul></nav></aside><section className="canvas" aria-live="polite" aria-labelledby="page-title"><ActiveView /></section><CustodyRail active={active} /><footer className="footer"><span>Keyboard shortcuts: {nav.map(([, label, key]) => <span className="shortcut" key={key}><kbd>{key}</kbd> {label}</span>)}</span><span>Content hash <code>{workbenchData.content_hash.slice(0, 20)}…</code></span></footer></main>;
}
